### ISSUE TITLE
Block Quotes Appear in Gray

### ISSUE THREAD

**Issue by jdauteri** [chnm/pwd-omeka-s#1]
Formatted block quotes appear in gray, making them hard to read against the background. 
![Screen Shot 2019-03-26 at 2 35 19 PM](https://user-images.githubusercontent.com/25283961/55024258-dfeca600-4fd4-11e9-9f03-a9dcc1a3a084.png)

**Comment by kimisgold** [comment]
Fixed in 79a6b7449d7d3a8599cc98a1f0e4fae8a31eaf78.
