### ISSUE TITLE
Update WP menu once Omeka menu is settled

### ISSUE THREAD

**Issue by mebrett** [chnm/pwd-omeka-s#5]
Once we decide on the final menu for the Omeka S side of things (and possibly after the move), update the wordpress menu so that it has the same options.

**Comment by mebrett** [comment]
Make sure that "Transcribe" points to http://dev.wardepartmentpapers.org/scripto/s/home/1/1/item and not the unstyled page at http://dev.wardepartmentpapers.org/scripto

**Comment by kimisgold** [comment]
The Wordpress theme should now be able to import the Omeka navigation, as of https://github.com/chnm/pwd-wordpress/commit/a11cc834349590d6c11067bf61126e62cd59ece1.
